"""empty message

Revision ID: 5ed4f870b95b
Revises: 0db651a2f4db
Create Date: 2019-07-24 14:34:32.514907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed4f870b95b'
down_revision = '0db651a2f4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('note', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
