"""empty message

Revision ID: 608bd9714015
Revises: ee892be1ad69
Create Date: 2019-07-02 08:21:45.084007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608bd9714015'
down_revision = 'ee892be1ad69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('stores', sa.Column('license', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'license')
    op.drop_column('stores', 'active')
    # ### end Alembic commands ###
