"""empty message

Revision ID: 710c73bc11f5
Revises: 85922ab15408
Create Date: 2019-07-10 09:12:10.392853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710c73bc11f5'
down_revision = '85922ab15408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=128), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
