"""empty message

Revision ID: 9eee82bad977
Revises: bb316dbf9d12
Create Date: 2019-07-11 11:20:23.137442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eee82bad977'
down_revision = 'bb316dbf9d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type_user', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type_user')
    # ### end Alembic commands ###
