"""empty message

Revision ID: d9bf73035a65
Revises: 5ed4f870b95b
Create Date: 2019-07-31 07:29:14.815109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bf73035a65'
down_revision = '5ed4f870b95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('store_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'store_name')
    # ### end Alembic commands ###
